task: davis
contrastive: False
contrastive_split: within

drug_featurizer: MorganFeaturizer
target_featurizer: ProtBertFeaturizer
latent_dimension: 1024
latent_distance: "Cosine"
model_size: "small"
prot_proj: "avg"
loss_type: "CE"
dropout: 0.0
sigmoid_scalar: 1

batch_size: 32
shuffle: True
num_workers: 0

epochs: 50
every_n_val: 1
lr: 1e-4
lr_t0: 10
InfoNCEWeight: 0.0
drug_layers: 1

replicate: 0

wandb_proj: ConPlexTrain
model_save_dir: ./best_models
