task: davis
contrastive_split: within

drug_featurizer: MorganFeaturizer
target_featurizer: SaProtFeaturizer
model_architecture: SimpleCoembeddingNoSigmoid
latent_dimension: 1024
latent_distance: "Cosine"
prot_proj: "agg"
loss_type: "CE"
num_heads_agg: 1
num_layers_target: 1
drug_layers: 1
dropout: 0.1

batch_size: 32
contrastive_batch_size: 256
shuffle: True
num_workers: 0

epochs: 250
every_n_val: 1
lr: 1e-4
lr_t0: 10
contrastive: True
contrastive_type: "default"
clr: 1e-5
clr_t0: 10
margin_fn: 'tanh_decay'
margin_max: 0.25
margin_t0: 20

replicate: 0
verbosity: 3

wandb_proj: ConPlexTrain
wandb_save: True
log_file: ./logs/scratch_testing.log
model_save_dir: ./best_models

